adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1.0e-08
cache_dir: null
checkpointing_steps: epoch
dataloader_num_workers: 4
dataset_name: cppe-5
gradient_accumulation_steps: 1
hub_model_id: null
hub_token: null
ignore_mismatched_sizes: true
image_square_size: 600
learning_rate: 5.0e-05
lr_scheduler_type: linear
max_train_steps: 21300
model_name_or_path: IDEA-Research/grounding-dino-tiny
num_train_epochs: 100
num_warmup_steps: 0
output_dir: grounding-dino-tiny-finetuned
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
push_to_hub: false
report_to: all
resume_from_checkpoint: null
seed: null
train_val_split: 0.15
trust_remote_code: false
use_auth_token: false
with_tracking: true
