tests_torch:
  docker:
    - image: huggingface/transformers-torch-light
  environment:
    OMP_NUM_THREADS: 1
    TRANSFORMERS_IS_CI: true
    PYTEST_TIMEOUT: 120
    RUN_PIPELINE_TESTS: false
    RUN_PT_TF_CROSS_TESTS: false
    RUN_PT_FLAX_CROSS_TESTS: false
  resource_class: 2xlarge
  parallelism: << pipeline.parameters.tests_torch_parallelism >>
  steps:
    - checkout
    - attach_workspace:
        at: test_preparation
