name: Build PR Documentation

on:
  pull_request:

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: build_pr_documentation
        run: |
          uname -a
          ls -la /home/
          gcloud auth list
