name: Build documentation

on:
  push:
    branches:
      - master
      - doc-builder*
      - v*-release

jobs:
   build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@workflow_templates
    with:
      commit_sha: ${{ github.sha }}
      package: transformers
      notebook_folder: transformers_doc
    secrets:
      token: ${{ secrets.HUGGINGFACE_PUSH }}
