name: Build PR Documentation

on:
  pull_request:

env:
  MY_TOKEN: 33445566

jobs:
  check_runners:
    name: Check Runners
    runs-on: [single-gpu,doc-tests-gpu]
    container:
      image: huggingface/transformers-all-latest-gpu
      options: --gpus 0 --shm-size "16gb" --ipc host -v /mnt/cache/.cache/huggingface:/mnt/cache/
    steps:
      - name: Hello
        shell: bash
        run: |
          ls -l
          echo ${MY_TOKEN:0:3}