name: Build PR Documentation

on:
  pull_request:

jobs:
  build:
    runs_on: [self-hosted, multi-gpu, docker-gpu]
    steps:
      - name: build_pr_documentation
        run: |
          whoami
          uname -a
          uptime
