name: Model templates runner

on:
  push:
    paths:
      - "src/**"
      - "tests/**"
      - ".github/**"
      - "templates/**"
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  run_tests_templates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Loading cache.
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: v1.2-tests_templates
          restore-keys: |
            v1.2-tests_templates-${{ hashFiles('setup.py') }}
            v1.2-tests_templates

      - name: Install dependencies
        run: |
          python fail