name: Self-hosted runner (AMD mi300 scheduled CI caller)

on:
  workflow_run:
    workflows: ["Self-hosted runner (AMD scheduled CI caller)"]
    branches: ["main"]
    types: [completed]
  push:
    branches:
      - run_amd_scheduled_ci_caller*

jobs:
  model-ci:
    name: Model CI
    uses: ./.github/workflows/self-scheduled-amd-2.yml
    with:
      job: run_models_gpu
      slack_report_channel: "#transformers-ci-daily-amd"
      runner: mi300
      docker: huggingface/transformers-pytorch-amd-gpu
      ci_event: Daily CI
    secrets: inherit
