wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: huggingface
    huggingface_version: 4.12.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1633445137
    t:
      1:
      - 1
      - 2
      - 3
      - 11
      4: 3.8.5
      5: 0.12.1
      6: 4.12.0.dev0
      8:
      - 5
